export const state = {
  currentLanguage: 'en',
  lastStatusPayload: null,
  rows: [],
  lastFilteredRows: [],
  currentDayData: null,
  minDate: null,
  maxDate: new Date(),
  chartRefs: {
    createdFound: null,
    sentConnected: null,
    connectedReplies: null,
    repliesPositive: null,
    positiveEvents: null,
    countryCreatedFound: null,
    countrySentConnected: null,
    countryConnectedReplies: null,
    countryRepliesPositive: null,
    countryPositiveEvents: null,
    countryConnected: null,
    countryReplies: null,
    countryPositive: null,
    countryEvents: null,
    weekCreatedFound: null,
    weekSentConnected: null,
    weekConnectedReplies: null,
    weekRepliesPositive: null,
    weekPositiveEvents: null,
    monthCreatedFound: null,
    monthSentConnected: null,
    monthConnectedReplies: null,
    monthRepliesPositive: null,
    monthPositiveEvents: null,
    lbCreated: null,
    lbSent: null,
    lbPositive: null,
    lbEvents: null,
    monthConversionRate: null,
    countryConversionRate: null,
    lbConversionRate: null,
    countryMonthlyPaired: null,
    leadMonthlyPaired: null,
    sourceConversionRate: null,
    sourceCreatedToSent: null,
    sourceSentToConnected: null,
    sourceConnectedToReplies: null,
    sourceRepliesToPositive: null,
    sourcePositiveToEvents: null
  },
  chartElements: {},
  aggregationCache: {
    dataHash: null,
    lastFilteredRows: null,
    funnel: null,
    funnelSummary: null,
    country: null,
    weekly: null,
    monthly: null,
    leaderboard: null,
    dailySnapshot: null,
    leadQuality: null,
    source: null,
    aging: null,
    timing: null,
    teamLoad: null,
    countrySegmentation: null
  },
  renderedTabs: {
    funnel: false,
    country: false,
    weekly: false,
    monthly: false,
    leaderboard: false,
    source: false,
    operations: false,
    timing: false
  },
  tableData: {
    funnelDropoff: null,
    leadQuality: [],
    aging: null,
    dailySnapshot: null,
    stepPerformance: null,
    sourceQuality: null,
    timing: null,
    teamLoad: null,
    countrySegmentation: null
  },
  filters: {
    country: 'all',
    source: 'all',
    generator: 'all'
  },
  tableControls: {
    teamLoad: {
      search: '',
      sortKey: 'activeLeadsAssigned',
      sortDir: 'desc'
    },
    countrySegmentation: {
      search: '',
      sortMetric: 'created',
      sortDir: 'desc'
    }
  },
  currentTheme: 'light',
  userHasExplicitTheme: false,
  rerenderAll: null,
  openModalCount: 0,
  serverSummary: null,
  summaryUnavailable: false,
  prefersDarkSchemeQuery: typeof window !== 'undefined' && window.matchMedia
    ? window.matchMedia('(prefers-color-scheme: dark)')
    : null
};
